package cli

import (
	"bufio"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"strings"
)

// RunInit handles "postern init" — interactive server setup.
func RunInit() {
	if len(os.Args) > 1 && (os.Args[1] == "--help" || os.Args[1] == "-h") {
		printInitHelp()
		return
	}

	// Warn if .env already exists
	if _, err := os.Stat(".env"); err == nil {
		fmt.Print(".env already exists. Overwrite? [y/N] ")
		reader := bufio.NewReader(os.Stdin)
		answer, _ := reader.ReadString('\n')
		if strings.TrimSpace(strings.ToLower(answer)) != "y" {
			fmt.Println("Aborted.")
			return
		}
	}

	reader := bufio.NewReader(os.Stdin)

	fmt.Printf("Listen address %s: ", dimStyle.Render("[:8080]"))
	addr, _ := reader.ReadString('\n')
	addr = strings.TrimSpace(addr)
	if addr == "" {
		addr = ":8080"
	}

	fmt.Printf("Base URL %s: ", dimStyle.Render("[http://localhost:8080]"))
	baseURL, _ := reader.ReadString('\n')
	baseURL = strings.TrimSpace(baseURL)
	if baseURL == "" {
		baseURL = "http://localhost:8080"
	}

	accessSecret, err := generateSecret(32)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating secret: %v\n", err)
		os.Exit(1)
	}
	refreshSecret, err := generateSecret(32)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating secret: %v\n", err)
		os.Exit(1)
	}
	agentSecret, err := generateSecret(32)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating secret: %v\n", err)
		os.Exit(1)
	}

	content := fmt.Sprintf(`# postern server configuration
# Generated by: postern init
# Review and edit before running: postern serve

JWT_ACCESS_SECRET=%s
JWT_REFRESH_SECRET=%s
AGENT_PROVISIONING_SECRET=%s
ADDR=%s
BASE_URL=%s

# Uncomment and configure as needed:
# DB_PATH=postern.db
# ENVIRONMENT=production
# OPS_ADDR=
# GATEWAY_URL=
# WS_ALLOWED_ORIGINS=
`, accessSecret, refreshSecret, agentSecret, addr, baseURL)

	if err := os.WriteFile(".env", []byte(content), 0600); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing .env: %v\n", err)
		os.Exit(1)
	}

	fmt.Println()
	fmt.Println(headingStyle.Render("Created .env"))
	fmt.Printf("  Listen:   %s\n", addr)
	fmt.Printf("  Base URL: %s\n", baseURL)
	fmt.Printf("  Secrets:  generated (32 bytes each)\n")
	fmt.Println()
	fmt.Println(headingStyle.Render("Next steps"))
	fmt.Printf("  1. Review .env and adjust settings\n")
	fmt.Printf("  2. Run: %s\n", cmdStyle.Render("postern serve"))
}

func printInitHelp() {
	printTitle("postern init", "generate server configuration")
	printHeading("Usage")
	printCmd("postern init", "Interactive setup — generates .env in the current directory")
	fmt.Println()
	printHeading("What it does")
	fmt.Printf("  Generates JWT secrets and writes a .env file you can review and edit.\n")
	fmt.Printf("  Does not start anything — you run %s when ready.\n", cmdStyle.Render("postern serve"))
}

func generateSecret(n int) (string, error) {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return hex.EncodeToString(b), nil
}
